export interface StudentReviewArchive {
  code: string;
  term: string;
  source: string;
  reviews: string[];
}

/**
 * Anonymous course feedback copied from the public IDEA Lab archive.
 * Keep the source URL for provenance; the site renders these entries statically.
 */
export const studentReviewArchives = {
  cose361Spring2026: {
    code: "COSE361",
    term: "Spring 2026",
    source: "https://idea.korea.ac.kr/teaching/cose361_spring_2026",
    reviews: [
  "없습니다",
  "감사했습니다 교수님 !",
  ".",
  "good",
  ".",
  "설명을 이해하기 쉽게 잘 해주셔서 수업을 따라가기 수월했습니다.",
  "This was my favorite class this semster, I really like the professor, I think he is a really good teacher and I like the course as well.",
  ".",
  "최고였습니다. 강의 내용, 과제, 시험, 강의 전반에 있어서 학생들이 깊은 이해를 할 수 있게 해주고 동시에 잘 따라올 수 있도록 여러 장치를 만들어 주셨습니다",
  "수업이 체계적이고 자세하게 설명해주신 덕분에 매우 얻어가는게 많았다.",
  ".",
  "좋았습니다",
  "인공지능을 위한 기반지식을 배울 수 있는 좋은 수업입니다.",
  "no",
  ".",
  "없습니다.",
  "교수님께서 영어를 너무 잘하셔서 영강임에도 강의 내용이 너무 잘 들어왔다. 덕분에 해당 과목에 쉽게 발을 들일 수 있었고, 강의 자료도 너무 깔끔해서 좋았다.",
  "개괄적인 수업으로 인공지능 전반에 대한 지식을 얻을 수 있었습니다. 감사합니다!",
  ".",
  "인공지능의 전반에 대해 알 수 있어 좋았습니다.",
  "단순 반응형 모델에서 출발해 상태 기반 탐색, 그리고 변수 기반 추론까지, 인공지능 문제를 바라보는 관점이 단계적으로 확장되는 흐름을 체계적으로 익힌 수업이었습니다.",
  ".",
  "수업이 좋아요",
  "정보대 교수님 GOAT",
  ".",
  "Before taking the class, I was determined not to do AI since everyone is researching about it. But this class make it so interesting that I am gonna do some AI related stuff in the future",
  "교수님께서 어려운 내용을 정말 쉽게 풀어서 설명해 주신 점이 인상 깊었다. 학생들의 편의를 많이 봐주시는 게 느껴지는 강의였다 (녹화 강의 업로드, 모의 문제 업로드, 과제 솔류션 제공). 강의자료도 잘 정리되어 있어서 수업 후에 복습하는 데 도움이 많이 되었다.",
  "없어요",
  "인공지능을 퀄리티 높게 배울 수 있어서 좋았습니다.",
  "좋은 수업 감사합니다.",
  "the professor help a lot for their students which made the class fun",
  "수업 이후 한국어 요약을 해주시는 점이 좋았습니다",
  "예시를 통해 적용 방법을 설명해주셔서 이해가 잘 되었습니다",
  "교수님이 친절하고 수업 내용 또한 유익했습니다.",
  "교수님께서 매우 친절하시고 학생들의 편의를 버ㅏ주십니다. 인공지능의 전반적인 내용에 대해 이해할 수 있었단 스압입니나",
  "인공지능의 논리적 원리에 대해 잘 알 수 있어서 너무 유익했어요",
  "실습을 살짝 늘리셔도 재밌을거같아요",
  "영어로 설명하기에 어려운 내용은 말하는 속도도 낮춰주시고, 한글로 다시 요약해주시는 등 학생들을 배려해주셔서 수월하게 학습할 수 있었습니다. 시험도 무작정 지엽적인 출제가 아닌, 인공지능의 학습 논리를 이해한 뒤 그를 활용해서 풀 수 있는 문제를 출제하여 공부의 효율을 높여주셨습니다.",
  "great",
  ".",
  ".",
  ".",
  "최고의 수업. 이해도 쉽고 강의 체계도 명확히 설명해주셔서 어떠한 부분을 공부하고 있는지 정확히 파악할 수 있었음.",
  "굿",
  "지금까지 들어본 정보대 전공수업 중 수업력이 가장 좋으셨습니다! and I love your cute kitty~",
  "좋았습니다",
  "fun and informative class",
  "유익한 강의",
  "학생들을 많이 배려해주시는게 느껴져서 감사했습니다. 고양이 귀여워요",
  ".",
  "기본적인 지식이 부족했음에도 그런학생들조차 이해하기 쉽게 강의해주시고 수업을 많이 준비한것이 보여서 너무 감사한 수업이였습니다. 얻어간 내용이 굉장히 많은 수업이였습니다. 감사합니다.",
  "진짜 최고의 강의였습니다. 전공에 거부감을 느끼는 학생이였는데 이번 강의를 통해 조금 흥미를 느끼게 되었습니다!! 정말 친절하시고 학생들을 위해 주시는 것 같습니다. 감사합니다",
  "영강이지만 설명을 잘 해주셔서 무리없이 한 학기 동안 강의랄 잘 따라갈 수 있었습니다.",
  "전반적으로 강의가 매우 좋았습니다. 수업자료도 알아보기 편했고, 교수님께서 영어도 잘 하셔서 수업 듣기도 편했습니다.",
  "굳굳굳",
  ".",
  "강의가 너무 체계적이었어고 수업도 너무 좋아서 다음 학기때도 강성구 교수님 수업을 듣고 싶습니다.",
  "강의 자료도 깔끔하고 수업도 너무 잘해주십니다! 적절한 예시와 exercise로 이해도 수월하고 시험대비하기도 좋았습니다. 교수님 사랑해여<3",
  "강의의 흐름 구성도 매끄럽고, 강의 자료도 이해하기 쉽게 구성돼있고, 교수님께서도 말을 천천히 해주셔서 수업 듣기가 편했습니다. 이 강의 덕분에 인공지능에 대한 전반적인 이해도가 향상되었습니다.",
  "없습니다",
  "교수님께서 학생들의 편의를 굉장히 신경써주시는 것 같다고 느꼈다. 강의 자료의 질, 가독성이 굉장히 좋고, 매 수업 후 한국어로 간략하게 요약을 해주시기 때문에 영어에 자신없는 학생들에게도 부담없이 들을 수 있는 강의라고 생각한다.",
  "지금까지 수강한 강의 중 가장 훌륭한 강의였다고 생각할 정도로 인상 깊었습니다. 적절한 난이도의 내용을 잘 짜인 강의로 이해하기 쉽게 설명해 주셔서 여러모로 유익했습니다. 기회가 된다면 강성규 교수님의 강의를 또 듣고 싶습니다.",
  "정말 좋은 수업 해주셔서 감사합니다",
  "고려대학교에서 들은 최고의 수업입니다.",
  "최고 퀄리티의 자료와 교수님의 강의력이 완성한 정보대학 최고의 수업이 아니지 않을까 싶습니다.",
  ".",
  "처음에 학습의 로드맵을 제시해 주시고 쭉 동일한 흐름으로 이어가는 부분이 매우 좋았고 한국어 서머리 시간 또한 매우 유익했다.",
  "Well structured course",
  "The lecture was conducted very fast, oftentimes requiring much external research over the same content covered in class.",
  "Very kind, passionate, and accommodating professor, amazing semester.",
  "좋은 강의었다고 생각합니다! 우선 교수님 설명이 굉장히 이해하기 쉬운 편이었고 과제량도 합리적인 편이었습니다. 다양한 개념을 배워갈 수 있어서 좋았습니다.",
  "Very interesting course. I was taught the use of concepts, how they were derived, and what they mean, as opposed to the past when I was told just how to use them. Thanks to that it is easier to recall those concepts.",
  "Lecture were delivered in an appropriate pace - all the material was possible to be understood during the class.",
  "Exams were using surprising applications of the taught material, making them more difficult, but the questions were more than possible to solve.",
  "전반적으로 굉장히 도움되고 의미있는 강의였습니다.",
  "The concepts were well explained. I enjoyed the class.",
  "This course was challenging and the professor was very clear with expectations and thorough with the teaching of the content.",
  ""
]
  },
  cose361Spring2025: {
    code: "COSE361",
    term: "Spring 2025",
    source: "https://sites.google.com/view/idea-koreauniv/teaching/cose361_spring_2025",
    reviews: [
  "전반적인 과정을 친절하게 설명하셔서 부족하더라도 따라갈 수 있음",
  ".",
  "감사합니다.",
  "ㅇㅇ",
  "없음",
  "머신러닝에 대해 학습할 수 있었습니다. 강의 초반에 교수님의 설명 방식에 적응하는 데 어려움을 겪었지만, 교수님께서 적극적으로 소통하시는 모습과 학생들의 의견이 반영된 강의로 잘 마무리할 수 있었습니다. 감사합니다.",
  "머신러닝 전반에 대해 잘 배울 수 있어서 좋았습니다. 인공지능(GPT)을 사용해보면 그 모호성과 랜덤성이 조금 별로라는 생각이 들기도 했는데, 이 수업에서는 비교적 선명한 방법론을 소개받을 수 있어서 정말 흥미로웠습니다.",
  "학생의 의견을 잘 들어주셔서 좋았습니다.",
  "학생들을 배려해주시고 수업 내용을 알차고 쉽게 설명해주십니다.",
  "수업은 재미있었습니다.",
  ".",
  "이번 학기 가장 재밌고 만족스러웠던 수업이었습니다. 수업 초반은 어려웠지만 교수님께서 지속적으로 학생들의 수준에 맞춰 설명해주시려 하고, 수업 자료도 최대한 구체적으로 작성해주시는 노력이 느껴져서 더 열심히 들을 수 있었습니다. 한 학기 동안 너무 즐겁게 수업 들었습니다. 감사합니다.",
  "수고하셨습니다!",
  "만족",
  "와... 정말 수업부터 과제, 시험까지 모든 것이 갓벽한 수업이었습니다!! 긴 말 필요 없어요. 그냥 최고입니다. 저 이렇게 배워가는 게 많은 수업은 처음이었습니다. 한 학기 동안 많은 것을 가르쳐주셔서 너무너무 감사합니다!!",
  "",
  "AI is a rapidly growing field and it is hard to learn everything in one class. However, this class effectively covered most of the significant topics in AI. The topics were challenging and difficult to understand without background, but the quality of the knowledge gained from this class heavily outweighs the challenge. The examination and projects were also helpful in helping me practice the topics learned. Overall, it was an excellent class.",
  "1",
  "인공지능에 대한 전반적인 지식을 체계적으로 습득할 수 있는 알찬 수업이었습니다. 교수님의 세심한 배려에 정말 감사드립니다.",
  "정보대학의 새로운 빛",
  "I understood the overall ideas of the subject. However, learning the small details was quite difficult.",
  "I withdrew from class midway.",
  "컴퓨터학과 전공필수인 인공지능 수업 중 빛이었습니다. 강성구 교수님 수업을 들었는데, 정말 좋았습니다.",
  "감사합니다 교수님",
  "교수님 잘 들었습니다!",
  ".",
  "This was my first time taking an AI class and I believe I learned a lot. The slides were very helpful, but I wish they were more detailed in explaining the topics. I also thought the assignments and homework were very difficult, as we didn't learn much coding in class. Everyone is at different levels of coding, so I understand it may not be challenging for some, but it was for me. Overall, I was able to learn more in this class. The professor also did well explaining the topics.",
  "해당 분야에 관심을 갖게 되는 계기가 되는 수업이었습니다. 감사합니다.",
  "Hard class but the best professor",
  "Despite the course itself being a highly difficult subject that discusses the important fundamentals of Artificial Intelligence, the entire course experience was very excellent. I think this stemmed from the professor’s enthusiasm and dedication to deliver the lectures with great quality, alongside the extended effort to make sure all students were accommodated throughout the entire course. Additional explanation in both Korean and English was provided, video recordings were always available for revision, and questions were always answered with utmost clarity. Not to mention, the professor’s attention to detail really shined in the high-quality, well-prepared lecture materials, and immediate/timely notices regarding urgent information such as changes in exam location. Wonderful experience!",
  ".",
  "너무 좋았습니다 수업",
  "현대 인공지능의 여러 도구들을 접하며 해당 분야에 대한 관심이 높아졌습니다.",
  "I like the class because the professor teaches so well. It covers a lot of content but not too heavily.",
  "The professor was very good and the videos he uploaded were extremely helpful. Very good course.",
  "수업 내용이 체계적이고 흥미로웠습니다. 인공지능의 기초를 배우기 적절하다고 생각합니다.",
  "Really great class and the professor was very helpful and understanding.",
  ".",
  "교수님이 학생들을 위하고 많이 고민하시는 게 느껴졌습니다.",
  "너무 좋은 교수님!",
  "없음",
  "좋은 수업 감사합니다.",
  "..................................",
  "The professor is very nice and passionate about the topic. He seems very knowledgeable and made an effort to communicate with the students regarding the course. The course was well structured and well taught.",
  "수업 마지막에 한국어 summary를 진행해주셔서 내용 보충에 도움이 되었습니다. 감사합니다.",
  "체계적이다",
  "교재가 너무 보기 좋았습니다.",
  "이번 학기 개인적으로 단연 최고의 강의였습니다. 완벽에 가까운 강의자료, 어려운 개념을 쉽게 풀어 설명해주시는 강의력, 그리고 학생들에 대한 배려와 유머까지. 수강하면서 정말 기분 좋은 강의였습니다. 감사합니다.",
  ".",
  "설문을 통해 강의 난이도를 낮추거나 시험 난이도를 조절하는 등 배려해주셔서 감사하다.",
  "",
  "정말 훌륭한 강의입니다. 강의 자체도 체계적이고 강의 자료도 학생들이 이해하기 쉽게 잘 정리되어 있습니다. 강의 영상을 올려주시는 것, 과제 솔루션을 제공해주시는 것, 시험 채점 기준을 공개해주시는 것 모두 학습 방향을 잡는 데에 정말 큰 도움이 되었습니다. 고려대 전체를 통틀어 정말 좋은 강의였습니다.",
  ".",
  "교수님이 너무 착하고 귀여우십니다. 학생들의 이해도를 바탕으로 유동적으로 수업 속도와 내용을 조정하셔서 인공지능 전반의 내용을 쉽게 이해할 수 있었습니다. 과제는 수업에서 배운 알고리즘 지식을 직접 구현하는 것이었는데, 부담되지 않고 재미있었습니다.",
  "강의가 너무 좋아서 다음 학기 수업은 국강이길!!",
  "I think this course is informative and easy to follow.",
  "The course was ok. However, the explanations (especially exercises, implementations, programming assignments) were not enough.",
  "",
  "I think overall the class was good and taught the concepts outlined in the syllabus. I greatly enjoyed applying those concepts in our projects as it was a great way to apply what we were learning.",
  "좋았다",
  "수업 내용과 자료 모두 좋았습니다!",
  "감사합니다.",
  "AI에 대해서 배울 수 있어서 좋았습니다. 수업이 흥미로웠습니다.",
  "강의 자료와 교수님은 너무 좋습니다.",
  "인공지능을 처음 배웠는데, 초반엔 기본 지식이 없어 따라가기 어려웠지만 덕분에 인공지능과 관련한 아주 기초적이고 대략적인 내용을 알 수 있게 되었습니다. 감사합니다 교수님!",
  "인공지능 강의 중 최고",
  "질문도 친절하게 받아주시고, 강의자료도 체계적으로 잘 되어 있어 이해하기 편했습니다. 감사합니다.",
  "",
  "좋은 수업 감사드립니다.",
  "인공지능이 문제 해결을 위해 어떤 방식으로 작동하는지에 대해 자세하게 배울 수 있어서 좋았습니다. 감사했습니다.",
  "",
  "Everything was perfect. The professor, the class content, the exam question and assignment system just make students want to try more.",
  "Very clear and easy to understand.",
  "인공지능의 개요를 알 수 있는 좋은 수업이었습니다. 영어로 진행되어 전달에 한계가 있다는 점은 이해하지만, 스탠포드 강의는 동일한 내용을 2/3 시간 안에 더 명확하게 전달해서 훨씬 더 많은 것을 배워갈 수 있었습니다. 스탠포드 강의처럼 수업을 진행하신다면, 수업 중 학생들과 자유롭게 질문을 주고받고 이해도도 훨씬 높아지는 알찬 수업이 될 것 같습니다.",
  ".",
  "X",
  "교수님 정말 대단하신 것 같고, 수업도 훌륭해서 배워가는 게 많았습니다.",
  "도움이 많이 된 강의입니다.",
  "강의력도 좋으시고, 수업도 좋고, 다만 시험 두 번은 힘들었습니다.",
  "수업 잘 들었습니다.",
  ".",
  ".",
  "이 수업 통해서 많은 것을 배웠습니다.",
  "수업 정말 잘 하시고, 과제와 시험 난이도도 적절해서 좋았습니다.",
  "좋았다",
  "It was a harder class than said.",
  "Very useful and enriching. I will continue to study AI and apply it in aspects of my life.",
  "강의 자료에서 교수님의 정성이 느껴질 만큼 너무 잘 참고하면서 학습할 수 있었습니다. 한 학기 동안 감사했습니다.",
  "."
]
  },
  data304Fall2025: {
    code: "DATA304",
    term: "Fall 2025",
    source: "https://idea.korea.ac.kr/teaching/data304_fall_2025",
    reviews: [
  "시험이 너무 어려웠어요",
  ".",
  "AI 시대에 적합한 최고의 학부 수업이었습니다.",
  "강의와 강의 자료 모두 완벽하고 매끄럽게 진행된 것 같습니다 배운게 많은 강의입미디",
  "*",
  "다양한 실습을 해볼 수 있어서 너무 좋았고, 무엇보다도 한 학기의 수업 전체가 큰 줄기 하나로 엮여있어 좋았습니다.",
  "대학교와서 2년동안 들은 강의중 나에게 가장 의미있는 강의. 그냥 이론 암기가 아니라 인사이트를 배울 수 있는 goat 강의 교수님 사랑합니다.",
  "수업이 체계적이고 알차게 구성되어 있어 좋았습니다. 매 수업마다 하나의 개념을 분명하게 이해할 수 있었으며, 모든 강의 내용이 유기적으로 구성되어 프로젝트에서 실제로 활용해 볼 수 있었던 점도 학습에 도움이 되었던 것 같습니다. 한 학기 동안 좋은 수업 제공해주셔서 감사합니다.",
  "한 학기 동안 감사했습니다!",
  ".",
  ".",
  "고려대학교에서 수강한 수업 중 가장 모든 면에서 완벽한 수업이었습니다. 열심히 준비하신 것이 분명한 수업 슬라이드 자료, 그 슬라이드를 기반으로 체계적으로 차근차근 이해하기 쉽게 전달을 중시한 수업, 이해를 돕기 위해 설계된 각 프로그래밍 과제들, 하나의 구체적인 현업 상의 태스크를 가정하고 진행한 수업의 내용을 모두 조합한 파이널 프로젝트, 단순 암기가 아닌 이해를 묻는 시험까지 최고였습니다. 이런 수업을 들을 수 있어 감사했고 정말 교수님의 진심이 느껴지는 수업이었습니다. 교수님께서 이 수강평을 보실지는 모르겠으나 만약에 보게 되신다면 교수님의 수업을 매우 재밌게 듣고 덕분에 많이 배워간 학생이 있다는 사실을 아셨으면 좋겠습니다. 이 수업을 준비하기 위해 들이신 정말 많은 고민과 노력에 조금이나마 보람이 되셨으면 좋겠습니다. 한 학기 동안 정말 감사했습니다.",
  "well made course",
  "So challenging course about vanguard tech strategies for nlp tools, ai software and real-world applications of data alaytics.",
  "빅 데이터를 실질적으로 어떻게 처리할 수 있는지 배울 수 있어 좋았다. 또한 특강으로 외부에서 와서 직접 현업에 사용되는 기술에 대해 배우게 되어 앞으로 어떤 방향으로 나아갈지 짐작할 수 있는 기회였다.",
  "정말 잘 짜여진 강의의 흐름과 강의자료를 바탕으로 교수님의 강의를 들으며 학습하니 정말 얻어간 것이 많았습니다. 수업 내용과 과제와 프로젝트 사이의 유기성이 강해서 더 깊게 배울 수 있었습니다. 감사합니다, 교수님.",
  "수업 마무리에 항상 해주시던 한국어 요약 덕분에 어려운 내용을 이해하기 더 용이했던 것 같습니다. 감사합니다.",
  "",
  ".",
  "시험 시간도 유동적으로 늘려주시고 학생들 배려를 많이 해주신 것 같아 감사드립니다. 다만 마지막 과제나 기말 고사의 난이도가 조금 어려웠던 느낌이 강해서 조금 아쉽습니다ㅠ",
  "강의자료가 매우 정리가 잘 되어있고 깔끔해서, 공부하고 정리하는 게 너무 편했습니다. 교수님께서 강의력이 너무 좋으셔서 복잡한 내용이라도 내가 어디에 집중을 해야할지를 알 수 있어 좋았습니다. 많은 노력을 들여 공부한 강의이지만, 그만큼 얻어가는 것들이 많아서 너무 보람차다고 생각합니다.",
  "수업을 통해 추천시스템 분야를 실제 데이터를 통해 배워볼 수 있어서 좋았다. programming assignment 와 final assignment 모두 굉장히 전문적으로 깊게 배운거 같다. 학점도 아주 너그럽게 주시는거 같다.",
  ".",
  "한 학기 간 고생 많으셨습니다.",
  ".",
  "감사합니다",
  "Overall, it was a great experience.",
  "감사합니다.",
  "",
  "The topics were very interesting",
  "수업 후에 한국어 요약을 해주셔서 이해하는데 큰 도움이 되었습니다. 실습을 통해 정확한 개념을 이해할 수 있었습니다. AWS를 사용하여 좋은 경험을 쌓은 것 같습니다.",
  "차근차근 수업을 잘 진행해주셔서 감사했습니다.",
  "수업이 굉장히 체계적으로 구성되어 있어, 교수님께서 전달하시고자 하는 바가 명확했습니다. 덕분에 재미있게 공부할 수 있었습니다. 파이널 프로젝트는 어려웠지만 많은 것을 얻어갈 수 있었습니다.",
  "감사합니다.",
  "The course was very interesting. The professor explains the content in a detailed, easy-to-understand manner. The tutorial classes for each assignment were helpful. Also, the cheat sheet for the exam was helpful, since there were many formulas in the course. However, I am not sure the AWS resources helped very much. I have always used Visual Studio Code for python assignments, and had no problem in this course (both for assignments and the final project).",
  "없음",
  "The course is well arranged and I really enjoy learning the content. The professor explained all concepts really well.",
  "amazing class! i learned tons of insights and the big picture explanation really helped a lot",
  ".",
  ".",
  "흥미로운 분야에 대해 체계적으로 학습할 수 있었으며 AWS를 활용하여 직접 실습까지 진행해볼 수 있어서 좋았다",
  "The class is well organised and the lecturer is very relax which made the learning very smooth and no pressure for students",
  ".",
  "Everything in this class were perfect from the first week until the last week!",
  "좋은 강의 감사합니다",
  "ㅇ",
  ".",
  ".",
  "2년간 대학생활 동안 들은 강의 중 단연코 최고였습니다 얻어가는 내용도 매우 많았고 교수님도 매우매우 친절하셔서 수업의 높은 난이도에도 불구하고 편하고 재미있게 학습할 수 있었습니다.",
  "AWS 자원을 아낌없이 제공해주신 덕분에 처음으로 이런 구현 과제에서 나름대로 좋은 성과를 거두고 돌아갑니다. 빅데이터분석이라하여 사실 수치데이터 분석을 상상했었는데, 텍스트 데이터에 대해서 이렇게 깊게 다루시는 것을 보고 제가 아직 식견이 좁았구나라고 생각이 들었습니다. 덕분에 IR과 GNN에 대해서 많이 배우고 갑니다!",
  ".",
  "텍스트 데이터 분석에 대한 전반적인 이해가 가능했습니다.",
  "너무 재밌게 잘 들었습니다.",
  ".",
  "Personally, I felt that the amount of content in this course is somewhat overwhelming, especially the GNN and the search part. I get the gist of the concept but I found the mechanism/algorithm to be quite challenging to understand and learn to implement. Other than challenging parts I mentioned, I like that this course offered different types of ML such as adversarial learning and self-supervised learning, this gave me extra tools at disposal whenever met with a data problem.",
  "좋은 강의였습니다. 비록 제 관심분야와 다르다는 것을 뒤늦게 알아차리긴 했지만 새로운 분야에 대해 깊이 알게되어 유익했습니다.",
  "잘 들었습니다",
  "Really good",
  "성적 평가 방법을 투명하게 공개해주시고, 학생들이 이 수업을 통해 실제로 이 기술들이 어떻게 이용되는가를 함께 전달해주고자 하는 교수님의 노력과 열정이 보이는 수업이었습니다. 수업에서 배운 기술을 어떻게 실생활에 적용할 수 있을지 잘 몰라 답답했던 저의 마음을 해소해주셨습니다. 한학기동안 좋은 강의 감사합니다.",
  ".",
  ".",
  "Amazon AWS 자원을 할당 받아서 다양한 것들을 배울 수 있었던 매우 훌륭한 강의",
  "파이널 프로젝트가 매우 어려웠지만 현실적인 task를 경험할 수 있어서 좋았습니다.",
  "제가 들어본 컴퓨터학과 수업 중 가장 유익했습니다. 급변하는 ai 시대에 전통적인 text mining, search, classification, semi-supervised learning 등의 기법들부터 더 advanced 한 방법론들까지 공부해볼 수 있는 시간이었습니다. 프로젝트와 시험이 다소 challenging 하긴했지만 수업과 관련하여 깊게 고민해볼 수 있는 의미 있는 시간들이었습니다.",
  "PPT도 이해가 쉽게 체계적으로 되어있고 실제 상황을 바탕으로 어떤 기법을 이용해서 해결할 것인지 등의 방향으로 제시가 되어 좋았던 것 같습니다.",
  "관련 주제 이해에 큰 도움이 되었습니다. 감사합니다.",
  "한학기동안 수고 많으셨습니다!",
  "좋은 강의 감사합니다.",
  "Without AWS, the assignment would have been hard since we need to download the pretrained model everytime. Please keep the AWS for next classes.",
  "감사합니다",
  "..",
  "없습니다",
  "실습을 할 때 제일 좋았던 시간인 것 같아요",
  "좋았어요",
  ".",
  "없습니다",
  ".",
  "좋습니다.",
  "이번 학기에 가장 듣길 잘했다고 생각했던 수업입니다. 이 분야에 관심 있는 어느 학생들에게 무조건 추천하고 싶습니다.",
  ".",
  "1학기에 이어서도 체계적인 수업을 들을 수 있어서 좋았습니다.",
  "The course extremely well planned and executed. I think the pace made sense and the assignments were made to be accessible."
]
  }
} satisfies Record<string, StudentReviewArchive>;

